apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mbx-cache
  labels: {app.kubernetes.io/name: mbx-cache, app.kubernetes.io/instance: {{ .Release.Name }}}
spec:
  selector: {app.kubernetes.io/name: mbx-cache, app.kubernetes.io/instance: {{ .Release.Name }}}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}

