{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-mbx-cache" .Release.Name) .Values.serviceAccount.name }}
  labels: {app.kubernetes.io/name: mbx-cache, app.kubernetes.io/instance: {{ .Release.Name }}}
{{- end }}

